// Copyright (c) 2026 Mete Balci
// SPDX-License-Identifier: Apache-2.0

// `THURVSA_VERSION` is set by build.rs to "<crate-ver> (<sha>[-dirty])".
// `option_env!` is required (not `env!`) because this file is also
// `include!`d by build.rs itself — at that point the env var doesn't
// exist yet, so we fall back to the bare crate version.
const THURVSA_VERSION_STR: &str = match option_env!("THURVSA_VERSION") {
    Some(v) => v,
    None => env!("CARGO_PKG_VERSION"),
};

#[derive(Parser)]
#[command(name = "thurvsa")]
#[command(about = "ThurVSA Management CLI", long_about = None)]
#[command(version = THURVSA_VERSION_STR)]
struct Cli {
    /// Global flags (`--config`, `--user`) shared with thurvtl.
    #[command(flatten)]
    args: shared_cli::GlobalArgs,

    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Volume management (create, list, info, destroy).
    Volume {
        #[command(subcommand)]
        action: VolumeAction,
    },

    /// System operations.
    System {
        #[command(subcommand)]
        action: SystemAction,
    },

    /// iSCSI CHAP credentials.
    ///
    /// Manages `<data_dir>/iscsi-users.json` -- the daemon reads it
    /// fresh on every login, so edits take effect on the next
    /// session without restart.
    Iscsi {
        #[command(subcommand)]
        action: IscsiAction,
    },

    /// NVMe-TCP TLS-PSK credentials.
    ///
    /// Manages `<data_dir>/nvmetcp-psks.json` -- the daemon reads it
    /// fresh on every TLS handshake, so edits take effect on the
    /// next session without restart.
    Nvmetcp {
        #[command(subcommand)]
        action: NvmetcpAction,
    },

    /// Configuration helpers (defaults yaml, systemd unit, shell completion).
    Config {
        #[command(subcommand)]
        action: shared_cli::ConfigAction,
    },
}

#[derive(Subcommand)]
enum SystemAction {
    /// Storage-backend operations.
    Storage {
        #[command(subcommand)]
        action: StorageAction,
    },

    /// Garbage-collect orphan chunks from the chunk pool.
    Gc {
        /// Show what would be deleted without actually deleting.
        #[arg(long)]
        dry_run: bool,

        /// Also delete orphan objects from the storage backend.
        ///
        /// Skipped by default — local cleanup is the common case.
        #[arg(long)]
        storage: bool,
    },

    /// Regenerate the admin HTTP self-signed TLS cert.
    ///
    /// Daemon-down only. Overwrites the cert/key files in place,
    /// re-deriving SANs (hostname, loopback, `http.tls.extra_sans`).
    /// Refuses unless the existing cert was auto-generated by the
    /// daemon — to replace an operator-supplied cert, delete the
    /// cert/key/.autogen files by hand first. Restart the daemon to
    /// serve the new cert.
    RegenerateCert,

    /// First-party alerting (email + webhook).
    ///
    /// Configure via the `alerting:` block in thurvsa.yaml; this
    /// subcommand inspects and tests live sinks. Daemon-routed
    /// only (no daemon-down fallback — alerting state lives only
    /// in the running daemon).
    Alerting {
        #[command(subcommand)]
        action: AlertingAction,
    },

    /// Probe the daemon's admin Unix socket.
    ///
    /// Connects to `<data_dir>/admin.sock`, calls `GET
    /// /api/v1/health`, and renders the daemon's identity (version,
    /// data dir, API version). Confirms the transport is reachable
    /// and that the daemon is the one this CLI's config points at.
    DaemonHealth {
        /// Emit the response as JSON for automation.
        #[arg(long)]
        json: bool,
    },

    /// Live activity screen — holds and redraws ~1s, Ctrl-C to exit.
    ///
    /// Daemon-routed. Streams a per-second snapshot over the admin
    /// socket: uptime, volumes online, iSCSI sessions, per-backend
    /// pool used/cap + backpressure, per-backend storage PUT/GET rate
    /// over the last 60s, audit events over the last 5m.
    Monitor,

    /// Audit-chain operations.
    Audit {
        #[command(subcommand)]
        action: AuditAction,
    },

    /// Dedup ratio and per-volume contribution.
    ///
    /// Walks every volume's pages.idx and computes logical (host
    /// writes), unique pool bytes, and exclusive vs shared per
    /// volume. Helps tune page size, chunking, and compression
    /// against real workloads.
    Stats {
        /// Emit the full report as JSON for automation.
        #[arg(long)]
        json: bool,
    },

    /// Volume-wide consistency check.
    Verify {
        /// Skip the storage-backend sweep (local-only audit).
        ///
        /// The storage sweep is the default — verifying without it
        /// leaves cold-bucket DR untested.
        #[arg(long)]
        skip_storage: bool,

        /// Per-volume breakdown (every error and warning).
        #[arg(long)]
        verbose: bool,

        /// Emit the full report as JSON for CI / automation.
        ///
        /// Replaces the human-readable text output.
        #[arg(long)]
        json: bool,

        /// Optional volume names to limit the sweep.
        volumes: Vec<String>,
    },
}

#[derive(Subcommand)]
enum AuditAction {
    /// Print recent audit entries (optionally follow with -f).
    ///
    /// Follow mode only watches today's file (rotated files don't
    /// grow). Works in both plain and tamper-evident modes.
    Tail {
        /// Follow new entries as they land.
        ///
        /// Implementation: poll today's file every 500 ms.
        #[arg(short, long)]
        follow: bool,

        /// Number of trailing entries before follow mode (default 20).
        #[arg(short = 'n', long, default_value = "20")]
        lines: usize,
    },

    /// Export entries in the requested date range.
    Export {
        /// Output format: `jsonl` or `csv`.
        ///
        /// `jsonl` writes one entry per line. `csv` produces flat
        /// columns; nested params are JSON-encoded into one cell.
        #[arg(long, value_parser = ["jsonl", "csv"], default_value = "jsonl")]
        format: String,

        /// Inclusive start date (YYYY-MM-DD).
        ///
        /// Default: unbounded (all available entries).
        #[arg(long)]
        from: Option<String>,

        /// Inclusive end date (YYYY-MM-DD).
        ///
        /// Default: unbounded.
        #[arg(long)]
        to: Option<String>,
    },

    /// Verify the tamper-evident chain end-to-end.
    ///
    /// Walks every entry from genesis to tail, recomputing
    /// entry_hash and verifying prev_hash linkage. Tamper-evident
    /// mode only; plain-mode files have no chain to verify. Exit
    /// codes: 0 chain valid, 1 break found, 2 file IO error,
    /// 3 plain-mode (unverifiable).
    Verify,

    /// Offline-verify a copy of an audit directory.
    ///
    /// No daemon required. Walks every entry under `--dir` and
    /// verifies the BLAKE3 chain. Use after the audit directory has
    /// been copied off-host (cold backup) and the operator wants to
    /// validate it without booting the producing daemon. Exit codes:
    /// 0 valid, 1 break detected, 2 I/O / parse error.
    VerifyOffline {
        /// Path to the audit directory to verify (typically the
        /// `audit/` subdirectory of a `data_dir` copy).
        #[arg(long)]
        dir: std::path::PathBuf,

        /// Emit the VerifyReport as JSON for automation.
        #[arg(long)]
        json: bool,
    },

    /// Operator-acknowledged chain reset after a verify failure.
    ///
    /// Writes an `audit.chain_reset` entry whose `prev_hash` is a
    /// sentinel `blake3:break:<old_hash>` so the break stays visible
    /// forever. The new chain anchors off the reset entry.
    Rotate {
        /// Required confirmation. Without this flag, refuses to run.
        #[arg(long)]
        accept_break: bool,
    },
}

#[derive(Subcommand)]
enum AlertingAction {
    /// Show configured alert sinks and dedup window.
    List {
        #[arg(long)]
        json: bool,
    },

    /// Fire a synthetic alert through one sink.
    ///
    /// Bypasses the rate limiter and event-class gate so the chosen
    /// sink fires regardless of config; useful for validating SMTP
    /// credentials or webhook URLs end-to-end without waiting for
    /// a real event.
    Test {
        /// Sink name from the YAML `alerting.sinks` list.
        sink: String,
        /// Severity tag on the synthetic alert.
        #[arg(long, value_parser = ["info", "warn", "error"], default_value = "warn")]
        severity: String,
    },
}

#[derive(Subcommand)]
enum StorageAction {
    /// Check storage-backend connectivity, auth, and read/write/delete.
    ///
    /// Always allowed — does not require the daemon to be stopped.
    Check,

    /// First-party storage-backend throughput benchmark (daemon-down).
    ///
    /// Drives parallel upload / download / delete against the named
    /// backend(s) defined under `storage.backends:` in the YAML conffile
    /// and prints parseable `[BENCH]` lines. Issues real backend API
    /// calls and transfers real bytes — runs against the operator's
    /// bucket, so expect non-zero cost on metered backends.
    Benchmark {
        /// Backend name to benchmark. Repeatable.
        ///
        /// Defaults to every backend defined under `storage.backends:`
        /// in the YAML conffile (lexicographic order).
        #[arg(long = "backend")]
        backends: Vec<String>,

        /// GiB per cell. Default 32.
        #[arg(long, default_value_t = 32)]
        total_gb: usize,

        /// MiB per upload. Default 8 matches the FastCDC chunk average.
        #[arg(long, default_value_t = 8)]
        chunk_size_mb: usize,

        /// Parallel in-flight uploads per cell. Default 16.
        #[arg(long, default_value_t = 16)]
        concurrency: usize,

        /// Sweep chunk size across this comma-separated list.
        #[arg(long, value_delimiter = ',')]
        chunk_size_mb_sweep: Vec<usize>,

        /// Sweep concurrency across this comma-separated list.
        #[arg(long, value_delimiter = ',')]
        concurrency_sweep: Vec<usize>,

        /// Skip the download phase.
        #[arg(long)]
        skip_download: bool,

        /// Bypass the sweep-preview prompt (scripted runs).
        #[arg(long)]
        yes: bool,
    },
}

#[derive(Subcommand)]
enum VolumeAction {
    /// Create a new volume.
    ///
    /// Tries the daemon's admin socket first; falls back to a
    /// daemon-down manifest write under `data_dir` when the
    /// socket is unreachable. The chosen backend, page size, and
    /// dedup scope are sticky for the volume's lifetime.
    Create {
        /// Volume name (1-64 chars: letters, digits, '-', '_').
        name: String,

        /// Logical volume size, e.g. `1T`, `500G`, `4096`.
        ///
        /// Binary units only: K=2^10, M=2^20, G=2^30, T=2^40, P=2^50.
        /// Bare integer = bytes. Trailing `B` / `iB` is accepted but
        /// ignored. Must be a multiple of the sector size (4 KiB).
        #[arg(long)]
        size: String,

        /// Storage backend name to bind this volume to.
        ///
        /// Required when thurvsa.yaml defines multiple entries under
        /// `storage.backends`; inferred when only one backend exists.
        #[arg(long)]
        backend: Option<String>,

        /// Page size — chunk unit for backend upload + disk cache.
        ///
        /// Power of two, multiple of the sector size. Default 64K.
        #[arg(long, default_value = "64K")]
        page_size: String,

        /// Dedup scope: `global` (default) or `local`.
        #[arg(long, value_parser = ["local", "global"], default_value = "global")]
        dedup: String,

        /// Mark the volume Write-Once-Read-Many.
        #[arg(long)]
        worm: bool,

        /// Enable at-rest encryption (requires --keystore).
        ///
        /// The daemon mints an AES-256 DEK at create time (unless
        /// --key-file supplies one) and wraps it with the --keystore
        /// backend. Sticky for the volume's lifetime.
        #[arg(long, requires = "keystore")]
        encrypt: bool,

        /// Supply the at-rest DEK from PATH instead of minting one.
        ///
        /// PATH must contain a 64-char hex string (32 raw bytes = AES-256).
        /// `openssl rand -hex 32` produces a valid file. Requires
        /// `--encrypt`; sticky for the volume's lifetime.
        #[arg(long, value_name = "PATH", requires = "encrypt")]
        key_file: Option<std::path::PathBuf>,

        /// Keystore backend that wraps this volume's DEK.
        ///
        /// References a name in `keystore.backends:` (YAML conffile).
        /// Required together with `--encrypt`. Sticky for the volume's
        /// lifetime.
        #[arg(long, value_name = "NAME", requires = "encrypt")]
        keystore: Option<String>,

        /// Where the DEK is minted (requires --encrypt).
        ///
        /// `daemon` (default) uses the daemon's OsRng then asks the
        /// backend to wrap. `backend` uses KMS GenerateDataKey or
        /// Vault transit/datakey (HSM-grade RNG, one fewer
        /// round-trip). Ignored for the `local` backend.
        #[arg(long, value_parser = ["daemon", "backend"], requires = "encrypt")]
        dek_source: Option<String>,

        /// Initial SYNCHRONIZE CACHE durability tier (mutable later
        /// via `volume modify --sync-after`).
        ///
        /// `storage` (default) — fsync waits until bytes are durable
        /// in the configured storage backend. Safest; matches the
        /// storage-backend-durable contract.
        ///
        /// `disk` — fsync waits until bytes are in the local pool.
        /// Faster; loses on daemon-host disk failure before the
        /// upload worker drains.
        ///
        /// `memory` — fsync is a no-op; dirty pages stay in RAM
        /// until the periodic flush worker tick. Fastest; loses on
        /// any crash. ZFS sync=disabled equivalent.
        #[arg(long, value_parser = ["storage", "disk", "memory"], default_value = "storage")]
        sync_after: String,

        /// Pin this volume to LUN N.
        ///
        /// Default auto-assigns the smallest unused LUN. Pinned LUNs
        /// keep `/dev/disk/by-path/...-lun-N` references stable when
        /// sibling volumes are added or removed. Refuses if N is
        /// already bound.
        #[arg(long, value_name = "N")]
        lun: Option<u64>,
    },

    /// List every volume.
    ///
    /// Reads the live LUN map via the admin socket; falls back to
    /// walking `<data_dir>/volumes/` when the socket is
    /// unreachable. The socket view includes the assigned LUN per
    /// volume; the offline view doesn't.
    List {
        /// Emit the response as JSON for automation.
        #[arg(long)]
        json: bool,
    },

    /// Show one volume's manifest.
    Info {
        /// Volume name.
        name: String,

        /// Emit the manifest as JSON for automation.
        #[arg(long)]
        json: bool,
    },

    /// Destroy a volume.
    ///
    /// Unregisters the volume from the live LUN map and removes
    /// its on-disk artifacts (manifest + page index). Per-volume
    /// chunks remain in the pool until the next GC sweep.
    /// Daemon-routed only — refuses with "is the daemon running?"
    /// when the admin socket is unreachable.
    Destroy {
        /// Volume name.
        name: String,

        /// Confirm destruction. Without this flag the command
        /// refuses; the volume contents are gone after a destroy.
        #[arg(long)]
        force: bool,
    },

    /// Modify a live volume's mutable settings.
    ///
    /// Daemon-routed only — refuses if the admin socket is
    /// unreachable. The flip takes effect on the next host
    /// SYNCHRONIZE CACHE; in-flight SYNCs finish under the
    /// previous mode.
    ///
    /// **The contract change is not signalled to the SCSI
    /// initiator.** A host fsync-heavy workload silently gains or
    /// loses its durability guarantee on a flip; pair flips with
    /// workload-level awareness.
    Modify {
        /// Volume name.
        name: String,

        /// New SYNCHRONIZE CACHE durability tier.
        ///
        /// See `volume create --sync-after` for the per-tier
        /// semantic. Flipping `storage → memory` is the dangerous
        /// direction — host fsyncs that previously meant
        /// "storage-durable" silently become no-ops; bytes the host
        /// believes are persisted are lost on the next crash.
        #[arg(long, value_parser = ["storage", "disk", "memory"])]
        sync_after: String,
    },

    /// Grow or shrink a volume's capacity.
    ///
    /// Daemon-routed only — refuses if the admin socket is
    /// unreachable. Grow is metadata-only (the page table is sparse), so
    /// it's instant. Shrink is non-destructive: it refuses on a WORM
    /// volume, when a persistent reservation is held, or when allocated
    /// data sits past the new end — free that range from the host first
    /// (resize the filesystem, then `fstrim`/`blkdiscard`) or use
    /// `--shrink-to-fit`. Connected hosts are signalled to re-read
    /// capacity (NVMe AER / iSCSI unit attention); the host OS may still
    /// need a rescan (`iscsiadm --rescan` / `nvme ns-rescan`).
    Resize {
        /// Volume name.
        name: String,

        /// New logical volume size, e.g. `2T`, `500G`, `8192`.
        ///
        /// Binary units only: K=2^10, M=2^20, G=2^30, T=2^40, P=2^50.
        /// Bare integer = bytes. Must be a multiple of the sector size
        /// (4 KiB) and at least one page. Conflicts with
        /// `--shrink-to-fit`; exactly one is required.
        #[arg(long, required_unless_present = "shrink_to_fit", conflicts_with = "shrink_to_fit")]
        size: Option<String>,

        /// Shrink to the smallest size that keeps all data.
        ///
        /// Auto-computes the target (the allocated high-water mark) so you
        /// don't have to. Resize the filesystem down first (e.g.
        /// `resize2fs`) so it fits. Conflicts with `--size`.
        #[arg(long)]
        shrink_to_fit: bool,
    },

    /// Per-volume key-management operations.
    Key {
        #[command(subcommand)]
        action: KeyAction,
    },

    /// Manage volume snapshots.
    ///
    /// A snapshot is a frozen point-in-time copy of the volume's page
    /// table, sharing chunks with the volume (copy-on-write). It is not
    /// host-visible — access its data by cloning it (`volume clone
    /// --from-snapshot`). Daemon-routed only.
    Snapshot {
        #[command(subcommand)]
        action: SnapshotAction,
    },

    /// Clone a volume into a new writable volume.
    ///
    /// Seeds the clone from a snapshot (`--from-snapshot`) or the
    /// source's live contents, sharing chunks copy-on-write. The clone
    /// is a new LUN — grant host admission before use; it does not
    /// inherit the source's grants. Encrypted sources are refused
    /// (issue #86). Daemon-routed only.
    Clone {
        /// Source volume name.
        source: String,

        /// Name for the new clone volume.
        new_name: String,

        /// Clone from this snapshot (else the source's live state).
        #[arg(long, value_name = "SNAP")]
        from_snapshot: Option<String>,

        /// Pin the clone to LUN N (default: smallest unused).
        #[arg(long, value_name = "N")]
        lun: Option<u64>,
    },
}

#[derive(Subcommand)]
enum SnapshotAction {
    /// Create a snapshot of a volume.
    Create {
        /// Volume name.
        volume: String,

        /// Snapshot name (1-64 chars: letters, digits, '-', '_').
        snapshot: String,
    },

    /// List a volume's snapshots.
    List {
        /// Volume name.
        volume: String,

        /// Emit the response as JSON for automation.
        #[arg(long)]
        json: bool,
    },

    /// Destroy a snapshot.
    Destroy {
        /// Volume name.
        volume: String,

        /// Snapshot name.
        snapshot: String,

        /// Confirm destruction. Without it the command refuses.
        #[arg(long)]
        force: bool,
    },
}

#[derive(Subcommand)]
enum KeyAction {
    /// Move a volume's DEK to a different keystore backend.
    ///
    /// Unwraps the existing DEK from the current keystore backend,
    /// asks the new backend to rewrap the same DEK, and updates the
    /// manifest atomically. Volume data is NOT rewritten — only the
    /// wrap-target moves. Daemon-down only; stop thurvsad first.
    Migrate {
        /// Volume name.
        name: String,

        /// New keystore backend name.
        ///
        /// Must exist under `keystore.backends:` in the YAML conffile.
        /// Refuses if it matches the volume's current keystore backend.
        #[arg(long)]
        to: String,

        /// Delete the local-keystore sidecar after migrating away.
        ///
        /// Off by default so the operator can roll back by reverting
        /// the manifest if the new backend turns out to be
        /// misconfigured. Re-run with this flag once you've verified
        /// the new backend works.
        #[arg(long)]
        purge_local: bool,
    },

    /// Export a volume's DEK to a passphrase-sealed file (JWE/PBES2).
    ///
    /// Cross-region DR + audit-compliant key custody. Output is a
    /// JWE Compact string (RFC 7516 + 7518 PBES2-HS512+A256KW /
    /// A256GCM), one base64 token storable in any escrow vehicle
    /// (vault, sealed envelope, secrets manager). Cryptographically
    /// bound to the volume UUID — a stolen envelope is useless
    /// against any other volume. Daemon-down only.
    Export {
        /// Volume name.
        name: String,

        /// Output file path. Refuses if the file already exists.
        #[arg(long)]
        to: std::path::PathBuf,

        /// PBKDF2 iteration count. Default tuned for ~1 s on
        /// modern x86_64; raise for stronger work factor at the
        /// cost of slower export/import. Mirrors
        /// `shared_keystore::passphrase_envelope::DEFAULT_P2C`.
        #[arg(long, default_value_t = 600_000)]
        iter: u32,
    },

    /// Import a passphrase-sealed DEK envelope into a volume.
    ///
    /// Unwraps the JWE envelope produced by `volume key export` and
    /// rewraps the DEK into the named keystore backend (or the
    /// single configured one). Refuses if the envelope's bound UUID
    /// doesn't match the volume's UUID, or if the volume's current
    /// keystore already holds an unwrappable DEK (use
    /// `volume key migrate` to swap wrap targets in place).
    /// Daemon-down only.
    Import {
        /// Volume name.
        name: String,

        /// JWE Compact envelope file path (produced by
        /// `volume key export`).
        #[arg(long)]
        from: std::path::PathBuf,

        /// Target keystore backend name to rewrap into. Optional if
        /// `keystore.backends:` defines exactly one entry.
        #[arg(long)]
        keystore: Option<String>,
    },
}

// ---------- iscsi noun ----------

#[derive(Subcommand)]
enum IscsiAction {
    /// CHAP user lifecycle.
    Users {
        #[command(subcommand)]
        action: IscsiUsersAction,
    },

    /// Mutual-CHAP target credential.
    ///
    /// Singleton (one identity the target presents back to every
    /// mutual-CHAP-enabled initiator). Stored at the top level of
    /// `iscsi-users.json` as `target_username` / `target_password`.
    Target {
        #[command(subcommand)]
        action: IscsiTargetAction,
    },
}

#[derive(Subcommand)]
enum IscsiUsersAction {
    /// List every CHAP user.
    List {
        /// Emit JSON for automation.
        #[arg(long)]
        json: bool,
    },

    /// Add a new CHAP user.
    ///
    /// Refuses if the username already exists; use `rotate` to
    /// change a password. CHAP secret must be at least 12 bytes
    /// (RFC 3720 §11.1.4).
    Add {
        /// Username (CHAP identity the initiator presents).
        name: String,

        /// Password as a CLI arg. Mutually exclusive with `--password-stdin`.
        ///
        /// Note: appears in shell history and process listings. Prefer
        /// `--password-stdin` for production / config-management use.
        #[arg(long, conflicts_with = "password_stdin")]
        password: Option<String>,

        /// Read the password from stdin (single line, trailing
        /// newline stripped). Mutually exclusive with `--password`.
        #[arg(long)]
        password_stdin: bool,

        /// Enable mutual CHAP (target authenticates back to the
        /// initiator). Requires `iscsi target set` to have been run.
        #[arg(long)]
        mutual_chap: bool,

        /// Partition the user is fenced to (VTL only; VSA ignores).
        #[arg(long)]
        partition: Option<String>,

        /// Volume the user is admitted to (repeatable, required).
        ///
        /// Every CHAP user must be admitted to at least one volume —
        /// access without an explicit volume allow-list is refused.
        /// Names must currently resolve to a volume. To change the
        /// admission set later, use `grant` / `revoke`.
        #[arg(long = "volume", value_name = "NAME", action = clap::ArgAction::Append, required = true, num_args = 1..)]
        volume: Vec<String>,
    },

    /// Grant a user access to one or more volumes.
    ///
    /// Idempotent set-union: already-granted volumes are no-ops.
    /// Refuses if any named volume doesn't currently exist.
    /// Existing sessions don't see the change until they re-login —
    /// admission is captured at login from `iscsi-users.json`.
    Grant {
        /// Username to grant access to.
        name: String,

        /// Volume to add to the user's allow-list (repeatable, required).
        #[arg(long = "volume", value_name = "NAME", action = clap::ArgAction::Append, required = true, num_args = 1..)]
        volume: Vec<String>,
    },

    /// Revoke a user's access to one or more volumes.
    ///
    /// Set-difference; non-admitted volumes are no-ops. Refuses if
    /// the revoke would leave the user with zero admitted volumes
    /// — use `remove` or `disable` to fully cut access. Existing
    /// sessions don't see the change until they re-login.
    Revoke {
        /// Username to revoke access from.
        name: String,

        /// Volume to remove from the user's allow-list (repeatable, required).
        #[arg(long = "volume", value_name = "NAME", action = clap::ArgAction::Append, required = true, num_args = 1..)]
        volume: Vec<String>,
    },

    /// Remove a CHAP user.
    Remove {
        /// Username to remove.
        name: String,
    },

    /// Disable a user without removing the entry.
    ///
    /// Login attempts get a "disabled" rejection. Distinct from
    /// `remove` so the entry keeps its audit-history continuity
    /// and can be re-enabled later without re-sharing the password.
    Disable {
        /// Username to disable.
        name: String,
    },

    /// Re-enable a previously disabled user.
    Enable {
        /// Username to re-enable.
        name: String,
    },

    /// Rotate a user's password with a grace window.
    ///
    /// Both the old and new password authenticate until the grace
    /// window expires (default 24h). Revert with `rotate USER
    /// --cancel`. Refuses if a rotation is already in progress
    /// (cancel the existing one first to avoid orphaning the
    /// previous-previous password).
    Rotate {
        /// Username to rotate.
        name: String,

        /// New password as a CLI arg. Mutually exclusive with
        /// `--password-stdin`.
        #[arg(long, conflicts_with_all = ["password_stdin", "cancel"])]
        password: Option<String>,

        /// Read the new password from stdin (single line).
        #[arg(long, conflicts_with = "cancel")]
        password_stdin: bool,

        /// Grace window during which both passwords remain valid.
        /// Humantime: `24h`, `5m`, `1d12h`. Default `24h`.
        #[arg(long, default_value = "24h", conflicts_with = "cancel")]
        grace: String,

        /// Cancel an in-flight rotation: drop the new password,
        /// restore the previous one as sole current. Errors if no
        /// rotation is in progress.
        #[arg(long)]
        cancel: bool,
    },
}

#[derive(Subcommand)]
enum IscsiTargetAction {
    /// Show the current target identity (password value hidden).
    Show {
        /// Emit JSON for automation.
        #[arg(long)]
        json: bool,
    },

    /// Set both target_username and target_password.
    ///
    /// Overwrites any prior values. Required when any user has
    /// `mutual_chap: true`. Password must be at least 12 bytes
    /// (RFC 3720 §11.1.4).
    Set {
        /// Target username (sent in `CHAP_N` during mutual auth).
        #[arg(long)]
        username: String,

        /// Password as a CLI arg. Mutually exclusive with `--password-stdin`.
        #[arg(long, conflicts_with = "password_stdin")]
        password: Option<String>,

        /// Read the password from stdin (single line).
        #[arg(long)]
        password_stdin: bool,
    },

    /// Clear both target_username and target_password.
    ///
    /// Mutual-CHAP requests fail with "Target password not
    /// configured" afterward.
    Clear,
}

// ---------- nvmetcp noun ----------

#[derive(Subcommand)]
enum NvmetcpAction {
    /// TLS-PSK lifecycle for NVMe-TCP hosts.
    Psks {
        #[command(subcommand)]
        action: NvmetcpPsksAction,
    },

    /// DH-HMAC-CHAP in-band auth lifecycle for NVMe-TCP hosts.
    Dhchap {
        #[command(subcommand)]
        action: NvmetcpDhchapAction,
    },
}

#[derive(Subcommand)]
enum NvmetcpPsksAction {
    /// List every registered host PSK.
    List {
        /// Emit JSON for automation.
        #[arg(long)]
        json: bool,
    },

    /// Add a new host PSK.
    ///
    /// `--key` is the `NVMeTLSkey-...` string the operator
    /// generates host-side with `nvme gen-tls-key`. CRC-validated
    /// CLI-side before sending to the daemon.
    Add {
        /// Initiator host NQN (must match `nvme connect --hostnqn`).
        #[arg(long)]
        host_nqn: String,

        /// `NVMeTLSkey-X:NN:base64:` interchange string.
        #[arg(long)]
        key: String,

        /// Volume the host is admitted to (repeatable, required).
        ///
        /// Every host PSK must be admitted to at least one volume.
        /// Names must currently resolve to a volume. To change the
        /// admission set later, use `grant` / `revoke`.
        #[arg(long = "volume", value_name = "NAME", action = clap::ArgAction::Append, required = true, num_args = 1..)]
        volume: Vec<String>,
    },

    /// Grant a host access to one or more volumes.
    Grant {
        /// Host NQN to grant access to.
        #[arg(long)]
        host_nqn: String,

        /// Volume to add to the host's allow-list (repeatable, required).
        #[arg(long = "volume", value_name = "NAME", action = clap::ArgAction::Append, required = true, num_args = 1..)]
        volume: Vec<String>,
    },

    /// Revoke a host's access to one or more volumes.
    ///
    /// Refuses if the revoke would leave the host with zero admitted
    /// volumes — use `remove` or `disable` to fully cut access.
    Revoke {
        /// Host NQN to revoke access from.
        #[arg(long)]
        host_nqn: String,

        /// Volume to remove from the host's allow-list (repeatable, required).
        #[arg(long = "volume", value_name = "NAME", action = clap::ArgAction::Append, required = true, num_args = 1..)]
        volume: Vec<String>,
    },

    /// Remove a host PSK.
    Remove {
        /// Host NQN to remove.
        #[arg(long)]
        host_nqn: String,
    },

    /// Disable a host PSK without removing the entry.
    Disable {
        /// Host NQN to disable.
        #[arg(long)]
        host_nqn: String,
    },

    /// Re-enable a previously disabled host PSK.
    Enable {
        /// Host NQN to re-enable.
        #[arg(long)]
        host_nqn: String,
    },

    /// Rotate a host's PSK with a grace window.
    ///
    /// Both old and new keys authenticate until the grace expires
    /// (default 24h). Revert with `rotate --host-nqn N --cancel`.
    Rotate {
        /// Host NQN to rotate.
        #[arg(long)]
        host_nqn: String,

        /// New `NVMeTLSkey-...` interchange string.
        #[arg(long, conflicts_with = "cancel")]
        key: Option<String>,

        /// Grace window (humantime: `24h`, `5m`, `1d12h`). Default `24h`.
        #[arg(long, default_value = "24h", conflicts_with = "cancel")]
        grace: String,

        /// Cancel an in-flight rotation: drop the new key, restore
        /// the previous one. Errors if no rotation is in progress.
        #[arg(long)]
        cancel: bool,
    },
}

#[derive(Subcommand)]
enum NvmetcpDhchapAction {
    /// List every registered host DH-HMAC-CHAP entry.
    List {
        /// Emit JSON for automation.
        #[arg(long)]
        json: bool,
    },

    /// Add a new host DH-HMAC-CHAP secret.
    ///
    /// `--key` is the `DHHC-1:...` secret generated host-side with
    /// `nvme gen-dhchap-key`. CRC-validated CLI-side before sending.
    /// `--ctrl-key` (optional) sets a controller secret for mutual
    /// auth (`nvme connect --dhchap-ctrl-secret`).
    Add {
        /// Initiator host NQN (must match `nvme connect --hostnqn`).
        #[arg(long)]
        host_nqn: String,

        /// `DHHC-1:NN:base64:` host secret.
        #[arg(long)]
        key: String,

        /// Optional `DHHC-1:...` controller secret (mutual auth).
        #[arg(long)]
        ctrl_key: Option<String>,

        /// Volume the host is admitted to (repeatable, required).
        #[arg(long = "volume", value_name = "NAME", action = clap::ArgAction::Append, required = true, num_args = 1..)]
        volume: Vec<String>,
    },

    /// Grant a host access to one or more volumes.
    Grant {
        /// Host NQN to grant access to.
        #[arg(long)]
        host_nqn: String,

        /// Volume to add to the host's allow-list (repeatable, required).
        #[arg(long = "volume", value_name = "NAME", action = clap::ArgAction::Append, required = true, num_args = 1..)]
        volume: Vec<String>,
    },

    /// Revoke a host's access to one or more volumes.
    ///
    /// Refuses if the revoke would leave the host with zero admitted
    /// volumes — use `remove` or `disable` to fully cut access.
    Revoke {
        /// Host NQN to revoke access from.
        #[arg(long)]
        host_nqn: String,

        /// Volume to remove from the host's allow-list (repeatable, required).
        #[arg(long = "volume", value_name = "NAME", action = clap::ArgAction::Append, required = true, num_args = 1..)]
        volume: Vec<String>,
    },

    /// Remove a host DH-HMAC-CHAP entry.
    Remove {
        /// Host NQN to remove.
        #[arg(long)]
        host_nqn: String,
    },

    /// Disable a host entry without removing it.
    Disable {
        /// Host NQN to disable.
        #[arg(long)]
        host_nqn: String,
    },

    /// Re-enable a previously disabled host entry.
    Enable {
        /// Host NQN to re-enable.
        #[arg(long)]
        host_nqn: String,
    },

    /// Set (or replace) a host's controller secret for mutual auth.
    SetCtrlKey {
        /// Host NQN.
        #[arg(long)]
        host_nqn: String,

        /// `DHHC-1:...` controller secret.
        #[arg(long)]
        key: String,
    },

    /// Clear a host's controller secret (disable mutual auth).
    ClearCtrlKey {
        /// Host NQN.
        #[arg(long)]
        host_nqn: String,
    },

    /// Rotate a host's DH-HMAC-CHAP secret with a grace window.
    ///
    /// Both old and new secrets authenticate until the grace expires
    /// (default 24h). Revert with `rotate --host-nqn N --cancel`.
    Rotate {
        /// Host NQN to rotate.
        #[arg(long)]
        host_nqn: String,

        /// New `DHHC-1:...` secret.
        #[arg(long, conflicts_with = "cancel")]
        key: Option<String>,

        /// Grace window (humantime: `24h`, `5m`, `1d12h`). Default `24h`.
        #[arg(long, default_value = "24h", conflicts_with = "cancel")]
        grace: String,

        /// Cancel an in-flight rotation: drop the new secret, restore
        /// the previous one. Errors if no rotation is in progress.
        #[arg(long)]
        cancel: bool,
    },
}

#[cfg(test)]
mod cli_tests {
    use super::*;
    use clap::CommandFactory;

    /// clap's own consistency check — catches conflicting arg ids,
    /// duplicate short flags, malformed `requires`/`conflicts_with`.
    #[test]
    fn command_tree_is_internally_consistent() {
        Cli::command().debug_assert();
    }

    fn parse(args: &[&str]) -> Result<Cli, clap::Error> {
        Cli::try_parse_from(args)
    }

    /// Parse `args`, then destructure to one expected `Commands`
    /// variant via `match`. The `_` arm yields `None` so the caller's
    /// `.expect()` reports a clear "wrong variant" failure rather than
    /// a bare `panic!`.
    #[test]
    fn volume_create_minimal() {
        let cli = parse(&["thurvsa", "volume", "create", "vol1", "--size", "1T"])
            .expect("valid create parses");
        let action = match cli.command {
            Commands::Volume { action } => Some(action),
            _ => None,
        }
        .expect("expected volume action");
        let fields = match action {
            VolumeAction::Create {
                name,
                size,
                page_size,
                dedup,
                worm,
                sync_after,
                lun,
                ..
            } => Some((name, size, page_size, dedup, worm, sync_after, lun)),
            _ => None,
        }
        .expect("expected volume create");
        let (name, size, page_size, dedup, worm, sync_after, lun) = fields;
        assert_eq!(name, "vol1");
        assert_eq!(size, "1T");
        // Defaults straight off the clap attributes.
        assert_eq!(page_size, "64K");
        assert_eq!(dedup, "global");
        assert!(!worm);
        assert_eq!(sync_after, "storage");
        assert!(lun.is_none());
    }

    #[test]
    fn volume_create_requires_size() {
        // --size is a required arg; omitting it is a parse error.
        assert!(parse(&["thurvsa", "volume", "create", "vol1"]).is_err());
    }

    #[test]
    fn volume_create_full_flag_set() {
        let cli = parse(&[
            "thurvsa",
            "volume",
            "create",
            "secret-vol",
            "--size",
            "500G",
            "--backend",
            "s3",
            "--page-size",
            "128K",
            "--dedup",
            "global",
            "--worm",
            "--encrypt",
            "--keystore",
            "vault",
            "--dek-source",
            "backend",
            "--sync-after",
            "disk",
            "--lun",
            "7",
        ])
        .expect("full flag set parses");
        let action = match cli.command {
            Commands::Volume { action } => Some(action),
            _ => None,
        }
        .expect("expected volume action");
        let create = match action {
            VolumeAction::Create {
                backend,
                dedup,
                worm,
                encrypt,
                keystore,
                dek_source,
                sync_after,
                lun,
                ..
            } => Some((
                backend, dedup, worm, encrypt, keystore, dek_source, sync_after, lun,
            )),
            _ => None,
        }
        .expect("expected volume create");
        let (backend, dedup, worm, encrypt, keystore, dek_source, sync_after, lun) = create;
        assert_eq!(backend.as_deref(), Some("s3"));
        assert_eq!(dedup, "global");
        assert!(worm);
        assert!(encrypt);
        assert_eq!(keystore.as_deref(), Some("vault"));
        assert_eq!(dek_source.as_deref(), Some("backend"));
        assert_eq!(sync_after, "disk");
        assert_eq!(lun, Some(7));
    }

    #[test]
    fn volume_create_encrypt_requires_keystore() {
        // `--encrypt` has `requires = "keystore"` — bare --encrypt fails.
        assert!(
            parse(&[
                "thurvsa", "volume", "create", "v", "--size", "1G", "--encrypt"
            ])
            .is_err()
        );
    }

    #[test]
    fn volume_create_key_file_requires_encrypt() {
        // `--key-file` has `requires = "encrypt"`.
        assert!(
            parse(&[
                "thurvsa",
                "volume",
                "create",
                "v",
                "--size",
                "1G",
                "--key-file",
                "/tmp/k",
            ])
            .is_err()
        );
    }

    #[test]
    fn volume_create_rejects_unknown_dedup() {
        // `--dedup` has a fixed value_parser list.
        assert!(
            parse(&[
                "thurvsa", "volume", "create", "v", "--size", "1G", "--dedup", "regional",
            ])
            .is_err()
        );
    }

    #[test]
    fn volume_create_rejects_unknown_sync_after() {
        assert!(
            parse(&[
                "thurvsa",
                "volume",
                "create",
                "v",
                "--size",
                "1G",
                "--sync-after",
                "ram",
            ])
            .is_err()
        );
    }

    #[test]
    fn volume_list_and_info_json_flag() {
        let cli = parse(&["thurvsa", "volume", "list", "--json"]).expect("list parses");
        assert!(matches!(
            cli.command,
            Commands::Volume {
                action: VolumeAction::List { json: true }
            }
        ));
        let cli = parse(&["thurvsa", "volume", "info", "vol1"]).expect("info parses");
        assert!(matches!(
            cli.command,
            Commands::Volume {
                action: VolumeAction::Info { name, json: false }
            } if name == "vol1"
        ));
    }

    #[test]
    fn volume_destroy_force_flag() {
        let cli =
            parse(&["thurvsa", "volume", "destroy", "vol1", "--force"]).expect("destroy parses");
        assert!(matches!(
            cli.command,
            Commands::Volume {
                action: VolumeAction::Destroy { name, force: true }
            } if name == "vol1"
        ));
    }

    #[test]
    fn volume_modify_sync_after() {
        let cli = parse(&["thurvsa", "volume", "modify", "vol1", "--sync-after", "memory"])
            .expect("modify parses");
        assert!(matches!(
            cli.command,
            Commands::Volume {
                action: VolumeAction::Modify { name, sync_after }
            } if name == "vol1" && sync_after == "memory"
        ));
        // --sync-after is required for modify.
        assert!(parse(&["thurvsa", "volume", "modify", "vol1"]).is_err());
    }

    #[test]
    fn volume_key_subcommands() {
        let cli = parse(&[
            "thurvsa", "volume", "key", "migrate", "vol1", "--to", "awskms",
        ])
        .expect("key migrate parses");
        assert!(matches!(
            cli.command,
            Commands::Volume {
                action: VolumeAction::Key {
                    action: KeyAction::Migrate { name, to, purge_local: false }
                }
            } if name == "vol1" && to == "awskms"
        ));

        let cli = parse(&[
            "thurvsa", "volume", "key", "export", "vol1", "--to", "/tmp/env",
        ])
        .expect("key export parses");
        assert!(matches!(
            cli.command,
            Commands::Volume {
                action: VolumeAction::Key {
                    action: KeyAction::Export { name, iter, .. }
                }
            } if name == "vol1" && iter == 600_000
        ));
    }

    #[test]
    fn system_gc_flags() {
        let cli =
            parse(&["thurvsa", "system", "gc", "--dry-run", "--storage"]).expect("gc parses");
        assert!(matches!(
            cli.command,
            Commands::System {
                action: SystemAction::Gc {
                    dry_run: true,
                    storage: true
                }
            }
        ));
    }

    #[test]
    fn system_verify_collects_volume_names() {
        let cli = parse(&[
            "thurvsa", "system", "verify", "--skip-storage", "--verbose", "vol1", "vol2",
        ])
        .expect("verify parses");
        let verify = match cli.command {
            Commands::System {
                action:
                    SystemAction::Verify {
                        skip_storage,
                        verbose,
                        json,
                        volumes,
                    },
            } => Some((skip_storage, verbose, json, volumes)),
            _ => None,
        }
        .expect("expected system verify");
        let (skip_storage, verbose, json, volumes) = verify;
        assert!(skip_storage);
        assert!(verbose);
        assert!(!json);
        assert_eq!(volumes, vec!["vol1", "vol2"]);
    }

    #[test]
    fn system_storage_benchmark_defaults_and_sweeps() {
        let cli = parse(&[
            "thurvsa",
            "system",
            "storage",
            "benchmark",
            "--backend",
            "s3",
            "--concurrency-sweep",
            "8,16,32",
        ])
        .expect("benchmark parses");
        let bench = match cli.command {
            Commands::System {
                action:
                    SystemAction::Storage {
                        action:
                            StorageAction::Benchmark {
                                backends,
                                total_gb,
                                chunk_size_mb,
                                concurrency,
                                concurrency_sweep,
                                ..
                            },
                    },
            } => Some((
                backends,
                total_gb,
                chunk_size_mb,
                concurrency,
                concurrency_sweep,
            )),
            _ => None,
        }
        .expect("expected storage benchmark");
        let (backends, total_gb, chunk_size_mb, concurrency, concurrency_sweep) = bench;
        assert_eq!(backends, vec!["s3"]);
        assert_eq!(total_gb, 32);
        assert_eq!(chunk_size_mb, 8);
        assert_eq!(concurrency, 16);
        assert_eq!(concurrency_sweep, vec![8, 16, 32]);
    }

    #[test]
    fn system_audit_tail_defaults() {
        let cli = parse(&["thurvsa", "system", "audit", "tail"]).expect("audit tail parses");
        assert!(matches!(
            cli.command,
            Commands::System {
                action: SystemAction::Audit {
                    action: AuditAction::Tail {
                        follow: false,
                        lines: 20
                    }
                }
            }
        ));
    }

    #[test]
    fn system_audit_export_rejects_bad_format() {
        // --format value_parser is ["jsonl", "csv"].
        assert!(parse(&["thurvsa", "system", "audit", "export", "--format", "xml"]).is_err());
        let cli = parse(&["thurvsa", "system", "audit", "export", "--format", "csv"])
            .expect("csv format parses");
        assert!(matches!(
            cli.command,
            Commands::System {
                action: SystemAction::Audit {
                    action: AuditAction::Export { format, .. }
                }
            } if format == "csv"
        ));
    }

    #[test]
    fn system_audit_rotate_accept_break() {
        let cli = parse(&["thurvsa", "system", "audit", "rotate", "--accept-break"])
            .expect("audit rotate parses");
        assert!(matches!(
            cli.command,
            Commands::System {
                action: SystemAction::Audit {
                    action: AuditAction::Rotate { accept_break: true }
                }
            }
        ));
    }

    #[test]
    fn system_alerting_test_rejects_bad_severity() {
        assert!(
            parse(&["thurvsa", "system", "alerting", "test", "sink1", "--severity", "panic"])
                .is_err()
        );
        let cli = parse(&["thurvsa", "system", "alerting", "test", "sink1"])
            .expect("alerting test parses");
        assert!(matches!(
            cli.command,
            Commands::System {
                action: SystemAction::Alerting {
                    action: AlertingAction::Test { sink, severity }
                }
            } if sink == "sink1" && severity == "warn"
        ));
    }

    #[test]
    fn iscsi_users_add_password_conflicts_with_stdin() {
        // `--password` conflicts_with `--password-stdin`.
        assert!(
            parse(&[
                "thurvsa",
                "iscsi",
                "users",
                "add",
                "alice",
                "--password",
                "hunter2-long",
                "--password-stdin",
                "--volume",
                "v1",
            ])
            .is_err()
        );
        // `--volume` is required: omitting it must fail to parse.
        assert!(
            parse(&[
                "thurvsa",
                "iscsi",
                "users",
                "add",
                "alice",
                "--password",
                "hunter2-long",
            ])
            .is_err()
        );
        let cli = parse(&[
            "thurvsa",
            "iscsi",
            "users",
            "add",
            "alice",
            "--password",
            "hunter2-long",
            "--mutual-chap",
            "--volume",
            "v1",
        ])
        .expect("users add parses");
        let add = match cli.command {
            Commands::Iscsi {
                action:
                    IscsiAction::Users {
                        action:
                            IscsiUsersAction::Add {
                                name,
                                password,
                                mutual_chap,
                                ..
                            },
                    },
            } => Some((name, password, mutual_chap)),
            _ => None,
        }
        .expect("expected users add");
        let (name, password, mutual_chap) = add;
        assert_eq!(name, "alice");
        assert_eq!(password.as_deref(), Some("hunter2-long"));
        assert!(mutual_chap);
    }

    #[test]
    fn iscsi_users_rotate_grace_default_and_cancel() {
        let cli = parse(&["thurvsa", "iscsi", "users", "rotate", "bob", "--cancel"])
            .expect("users rotate --cancel parses");
        assert!(matches!(
            cli.command,
            Commands::Iscsi {
                action: IscsiAction::Users {
                    action: IscsiUsersAction::Rotate { name, grace, cancel: true, .. }
                }
            } if name == "bob" && grace == "24h"
        ));
        // `--password` conflicts_with `--cancel`.
        assert!(
            parse(&[
                "thurvsa",
                "iscsi",
                "users",
                "rotate",
                "bob",
                "--cancel",
                "--password",
                "newpass-long12",
            ])
            .is_err()
        );
    }

    #[test]
    fn iscsi_target_set_requires_username() {
        assert!(parse(&["thurvsa", "iscsi", "target", "set"]).is_err());
        let cli = parse(&[
            "thurvsa",
            "iscsi",
            "target",
            "set",
            "--username",
            "tgt",
            "--password",
            "secret-pass12",
        ])
        .expect("target set parses");
        assert!(matches!(
            cli.command,
            Commands::Iscsi {
                action: IscsiAction::Target {
                    action: IscsiTargetAction::Set { username, .. }
                }
            } if username == "tgt"
        ));
    }

    #[test]
    fn nvmetcp_psks_add_and_rotate() {
        // `--volume` is required for psks add: omitting it must fail.
        assert!(
            parse(&[
                "thurvsa",
                "nvmetcp",
                "psks",
                "add",
                "--host-nqn",
                "nqn.host",
                "--key",
                "NVMeTLSkey-1:01:abc:",
            ])
            .is_err()
        );
        let cli = parse(&[
            "thurvsa",
            "nvmetcp",
            "psks",
            "add",
            "--host-nqn",
            "nqn.host",
            "--key",
            "NVMeTLSkey-1:01:abc:",
            "--volume",
            "v1",
        ])
        .expect("psks add parses");
        assert!(matches!(
            cli.command,
            Commands::Nvmetcp {
                action: NvmetcpAction::Psks {
                    action: NvmetcpPsksAction::Add { host_nqn, key, .. }
                }
            } if host_nqn == "nqn.host" && key == "NVMeTLSkey-1:01:abc:"
        ));

        let cli = parse(&[
            "thurvsa", "nvmetcp", "psks", "rotate", "--host-nqn", "nqn.host", "--cancel",
        ])
        .expect("psks rotate --cancel parses");
        assert!(matches!(
            cli.command,
            Commands::Nvmetcp {
                action: NvmetcpAction::Psks {
                    action: NvmetcpPsksAction::Rotate { grace, cancel: true, .. }
                }
            } if grace == "24h"
        ));
    }

    #[test]
    fn config_completion_subcommand() {
        let cli = parse(&["thurvsa", "config", "defaults"]).expect("config defaults parses");
        assert!(matches!(
            cli.command,
            Commands::Config {
                action: shared_cli::ConfigAction::Defaults
            }
        ));
    }

    #[test]
    fn global_config_flag_threads_through() {
        let cli = parse(&["thurvsa", "--config", "/etc/x.yaml", "volume", "list"])
            .expect("global --config parses");
        assert_eq!(cli.args.config.as_deref(), Some("/etc/x.yaml"));
    }

    #[test]
    fn unknown_subcommand_is_rejected() {
        assert!(parse(&["thurvsa", "frobnicate"]).is_err());
        // Missing subcommand entirely.
        assert!(parse(&["thurvsa"]).is_err());
    }
}
