// Copyright (c) 2026 Mete Balci
// SPDX-License-Identifier: Apache-2.0

//! Self-signed cert+key generation + on-disk persistence.
//!
//! Persists a daemon-managed secret at mode 0600 via an atomic
//! tmp-sidecar rename (load-or-create on boot).

use std::fs::{self, Permissions};
use std::io::{ErrorKind, Write};
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use rustls_pki_types::pem::PemObject;
use rustls_pki_types::{CertificateDer, PrivateKeyDer};
use sha2::{Digest, Sha256};

use crate::config::TlsConfig;

/// File mode on the generated cert (world-readable, owner-writable).
const CERT_MODE: u32 = 0o644;
/// File mode on the generated key (owner-only).
const KEY_MODE: u32 = 0o600;
/// Self-signed cert validity: ten years. Self-signed is already
/// trust-on-first-use; rotation cadence is left to the operator.
const SELF_SIGNED_DAYS: u32 = 3650;

/// Reports whether the cert/key were freshly generated by this call
/// or loaded as-is, plus the leaf-cert SHA-256 fingerprint (hex,
/// lowercase) so the caller can log it at boot.
#[derive(Debug, Clone)]
pub struct CertGenerationOutcome {
    pub was_generated: bool,
    pub cert_fingerprint_sha256: String,
    pub sans: Vec<String>,
}

/// Result of [`regenerate_cert`].
#[derive(Debug, Clone)]
pub struct RegenerateOutcome {
    /// SHA-256 fingerprint (hex, lowercase) of the newly written cert.
    pub cert_fingerprint_sha256: String,
    /// SANs baked into the new cert.
    pub sans: Vec<String>,
    /// Fingerprint of the cert that was replaced, or `None` when no
    /// cert was on disk before this call.
    pub prior_fingerprint: Option<String>,
}

/// Load `tls.cert_file` + `tls.key_file`, or generate-and-persist a
/// fresh self-signed pair if both files are absent.
///
/// Branches by file presence:
/// - both present → load + parse, return `was_generated: false`.
/// - both absent → generate ECDSA P-256, persist, return `was_generated: true`.
/// - exactly one absent → hard error naming the missing file.
pub fn load_or_generate_cert_key(
    tls: &TlsConfig,
) -> Result<(
    Vec<CertificateDer<'static>>,
    PrivateKeyDer<'static>,
    CertGenerationOutcome,
)> {
    let cert_meta = fs::metadata(&tls.cert_file);
    let key_meta = fs::metadata(&tls.key_file);

    match (cert_meta, key_meta) {
        (Ok(_), Ok(_)) => load_existing(&tls.cert_file, &tls.key_file),
        (Err(ce), Err(ke))
            if ce.kind() == ErrorKind::NotFound && ke.kind() == ErrorKind::NotFound =>
        {
            generate_and_persist(&tls.cert_file, &tls.key_file, &tls.extra_sans)
        }
        (Ok(_), Err(ke)) if ke.kind() == ErrorKind::NotFound => bail!(
            "TLS key file {key:?} missing but cert file {cert:?} present; refusing to half-generate \
             (remove both to trigger auto-generation, or supply both)",
            key = tls.key_file,
            cert = tls.cert_file,
        ),
        (Err(ce), Ok(_)) if ce.kind() == ErrorKind::NotFound => bail!(
            "TLS cert file {cert:?} missing but key file {key:?} present; refusing to half-generate \
             (remove both to trigger auto-generation, or supply both)",
            cert = tls.cert_file,
            key = tls.key_file,
        ),
        (Err(e), _) => {
            Err(anyhow::Error::from(e).context(format!("stat TLS cert file {:?}", tls.cert_file)))
        }
        (_, Err(e)) => {
            Err(anyhow::Error::from(e).context(format!("stat TLS key file {:?}", tls.key_file)))
        }
    }
}

/// Regenerate the self-signed cert+key, refusing to clobber a cert the
/// daemon did not generate.
///
/// A daemon-generated cert always has a sibling `.autogen` marker (see
/// [`marker_path`]) holding its leaf SHA-256 fingerprint. This call:
///
/// - **no cert on disk** → generate a fresh pair, `prior_fingerprint:
///   None`.
/// - **cert present, marker present and fingerprint-matched** →
///   overwrite cert + key + marker, `prior_fingerprint: Some(old)`.
/// - **cert present, marker absent or mismatched** → `Err` — the cert
///   was supplied by the operator (or predates marker support); the
///   caller must remove the files by hand to force a fresh cert.
///
/// Binding the marker to the fingerprint means a swapped-in operator
/// cert left next to a stale marker is still correctly refused.
pub fn regenerate_cert(tls: &TlsConfig) -> Result<RegenerateOutcome> {
    let prior_fingerprint = match fs::metadata(&tls.cert_file) {
        Err(e) if e.kind() == ErrorKind::NotFound => None,
        Err(e) => {
            return Err(
                anyhow::Error::from(e).context(format!("stat TLS cert file {:?}", tls.cert_file))
            );
        }
        Ok(_) => {
            let cert_bytes = fs::read(&tls.cert_file)
                .with_context(|| format!("reading TLS cert file {:?}", tls.cert_file))?;
            let certs = parse_certs(&cert_bytes, &tls.cert_file)?;
            let existing_fp = fingerprint_leaf(&certs)?;
            let marker = marker_path(&tls.cert_file);

            let marker_fp = match fs::read_to_string(&marker) {
                Ok(s) => s,
                Err(e) if e.kind() == ErrorKind::NotFound => bail!(
                    "refusing to regenerate: {cert:?} has no {marker:?} marker — it was not \
                     auto-generated by the daemon. To replace it with a fresh self-signed \
                     cert, delete {cert:?}, {key:?} and {marker:?} by hand, then re-run.",
                    cert = tls.cert_file,
                    key = tls.key_file,
                ),
                Err(e) => {
                    return Err(anyhow::Error::from(e)
                        .context(format!("reading TLS cert marker {marker:?}")));
                }
            };
            if !marker_fp.trim().eq_ignore_ascii_case(&existing_fp) {
                bail!(
                    "refusing to regenerate: {cert:?} fingerprint {existing_fp} does not match \
                     its {marker:?} marker ({marker_fp}) — an operator-supplied cert is in \
                     place. To replace it with a fresh self-signed cert, delete {cert:?}, \
                     {key:?} and {marker:?} by hand, then re-run.",
                    cert = tls.cert_file,
                    key = tls.key_file,
                    marker_fp = marker_fp.trim(),
                );
            }
            Some(existing_fp)
        }
    };

    let (_certs, _key, outcome) =
        generate_and_persist(&tls.cert_file, &tls.key_file, &tls.extra_sans)?;
    Ok(RegenerateOutcome {
        cert_fingerprint_sha256: outcome.cert_fingerprint_sha256,
        sans: outcome.sans,
        prior_fingerprint,
    })
}

fn load_existing(
    cert_path: &Path,
    key_path: &Path,
) -> Result<(
    Vec<CertificateDer<'static>>,
    PrivateKeyDer<'static>,
    CertGenerationOutcome,
)> {
    let cert_bytes =
        fs::read(cert_path).with_context(|| format!("reading TLS cert file {cert_path:?}"))?;
    let key_bytes =
        fs::read(key_path).with_context(|| format!("reading TLS key file {key_path:?}"))?;

    let certs = parse_certs(&cert_bytes, cert_path)?;
    let key = parse_key(&key_bytes, key_path)?;
    let fingerprint = fingerprint_leaf(&certs)?;
    let sans = vec![];

    Ok((
        certs,
        key,
        CertGenerationOutcome {
            was_generated: false,
            cert_fingerprint_sha256: fingerprint,
            sans,
        },
    ))
}

fn generate_and_persist(
    cert_path: &Path,
    key_path: &Path,
    extra_sans: &[String],
) -> Result<(
    Vec<CertificateDer<'static>>,
    PrivateKeyDer<'static>,
    CertGenerationOutcome,
)> {
    let sans = build_sans(extra_sans);
    let cn = sans
        .first()
        .cloned()
        .unwrap_or_else(|| "localhost".to_string());

    let key_pair = rcgen::KeyPair::generate_for(&rcgen::PKCS_ECDSA_P256_SHA256)
        .context("generating ECDSA P-256 key pair")?;

    let mut params = rcgen::CertificateParams::new(sans.clone()).context("building cert params")?;
    params
        .distinguished_name
        .push(rcgen::DnType::CommonName, &cn);
    let now = time::OffsetDateTime::now_utc();
    params.not_before = now;
    params.not_after = now + time::Duration::days(i64::from(SELF_SIGNED_DAYS));

    let cert = params
        .self_signed(&key_pair)
        .context("self-signing certificate")?;

    let cert_pem = cert.pem();
    let key_pem = key_pair.serialize_pem();

    persist_with_mode(cert_path, cert_pem.as_bytes(), CERT_MODE)
        .with_context(|| format!("writing TLS cert to {cert_path:?}"))?;
    persist_with_mode(key_path, key_pem.as_bytes(), KEY_MODE)
        .with_context(|| format!("writing TLS key to {key_path:?}"))?;

    let cert_bytes = fs::read(cert_path)?;
    let key_bytes = fs::read(key_path)?;
    let certs = parse_certs(&cert_bytes, cert_path)?;
    let key = parse_key(&key_bytes, key_path)?;
    let fingerprint = fingerprint_leaf(&certs)?;

    // Marker sidecar: records the fingerprint so `regenerate_cert` can
    // later tell this daemon-generated cert from an operator-supplied
    // one. Written after the cert/key rename so a crash never leaves a
    // marker without its cert.
    let marker = marker_path(cert_path);
    persist_with_mode(&marker, fingerprint.as_bytes(), CERT_MODE)
        .with_context(|| format!("writing TLS cert marker to {marker:?}"))?;

    Ok((
        certs,
        key,
        CertGenerationOutcome {
            was_generated: true,
            cert_fingerprint_sha256: fingerprint,
            sans,
        },
    ))
}

/// Build the SAN list: hostname (if not "localhost"), the universal
/// loopback trio, then any operator-declared `extra_sans`.
fn build_sans(extra_sans: &[String]) -> Vec<String> {
    let mut sans: Vec<String> = Vec::with_capacity(4 + extra_sans.len());
    if let Ok(host) = nix::unistd::gethostname()
        && let Some(s) = host.to_str()
    {
        let s = s.trim();
        if !s.is_empty() && s != "localhost" {
            sans.push(s.to_string());
        }
    }
    sans.push("localhost".to_string());
    sans.push(IpAddr::V4(Ipv4Addr::LOCALHOST).to_string());
    sans.push(IpAddr::V6(Ipv6Addr::LOCALHOST).to_string());
    sans.extend(extra_sans.iter().cloned());
    sans
}

fn parse_certs(pem: &[u8], path: &Path) -> Result<Vec<CertificateDer<'static>>> {
    let certs = CertificateDer::pem_slice_iter(pem)
        .collect::<std::result::Result<Vec<_>, _>>()
        .with_context(|| format!("parsing TLS cert PEM at {path:?}"))?;
    if certs.is_empty() {
        bail!("TLS cert file {path:?} contains no CERTIFICATE blocks");
    }
    Ok(certs)
}

fn parse_key(pem: &[u8], path: &Path) -> Result<PrivateKeyDer<'static>> {
    PrivateKeyDer::from_pem_slice(pem)
        .with_context(|| format!("parsing TLS key PEM at {path:?} (no PRIVATE KEY block?)"))
}

fn fingerprint_leaf(certs: &[CertificateDer<'_>]) -> Result<String> {
    let leaf = certs
        .first()
        .ok_or_else(|| anyhow::anyhow!("cert chain unexpectedly empty"))?;
    let digest = Sha256::digest(leaf.as_ref());
    Ok(hex::encode(digest))
}

/// Atomic write to `path` at `mode`:
/// `create_dir_all` parent → `OpenOptions::mode(...)` → write → sync
/// → defensive `set_permissions` → `rename`.
fn persist_with_mode(path: &Path, bytes: &[u8], mode: u32) -> Result<()> {
    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        fs::create_dir_all(parent)?;
    }
    let tmp = tmp_sidecar(path);
    {
        let mut f = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(mode)
            .open(&tmp)?;
        f.write_all(bytes)?;
        f.sync_all()?;
    }
    fs::set_permissions(&tmp, Permissions::from_mode(mode))?;
    fs::rename(&tmp, path)?;
    Ok(())
}

fn tmp_sidecar(path: &Path) -> PathBuf {
    let mut name = path
        .file_name()
        .map(|n| n.to_os_string())
        .unwrap_or_default();
    name.push(".tmp");
    path.with_file_name(name)
}

/// Sidecar path recording the SHA-256 fingerprint of a
/// daemon-generated leaf cert (`<cert_file>.autogen`). Its presence
/// plus a matching fingerprint is how [`regenerate_cert`] tells a
/// daemon-generated cert from an operator-supplied one.
fn marker_path(cert_path: &Path) -> PathBuf {
    let mut name = cert_path
        .file_name()
        .map(|n| n.to_os_string())
        .unwrap_or_default();
    name.push(".autogen");
    cert_path.with_file_name(name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::MetadataExt;
    use tempfile::TempDir;

    fn tls(dir: &TempDir) -> TlsConfig {
        TlsConfig {
            cert_file: dir.path().join("cert.pem"),
            key_file: dir.path().join("key.pem"),
            client_ca_file: None,
            extra_sans: vec![],
        }
    }

    #[test]
    fn auto_gen_creates_cert_and_key_when_both_missing() {
        let dir = TempDir::new().expect("tempdir");
        let cfg = tls(&dir);

        let (certs, _key, outcome) =
            load_or_generate_cert_key(&cfg).expect("auto-generate succeeds");

        assert!(outcome.was_generated);
        assert!(!outcome.cert_fingerprint_sha256.is_empty());
        assert!(outcome.sans.contains(&"localhost".to_string()));
        assert!(outcome.sans.contains(&"127.0.0.1".to_string()));
        assert!(outcome.sans.contains(&"::1".to_string()));
        assert_eq!(certs.len(), 1);

        let cert_mode = fs::metadata(&cfg.cert_file).expect("cert meta").mode() & 0o777;
        let key_mode = fs::metadata(&cfg.key_file).expect("key meta").mode() & 0o777;
        assert_eq!(cert_mode, CERT_MODE, "cert mode");
        assert_eq!(key_mode, KEY_MODE, "key mode");
    }

    #[test]
    fn errors_when_only_key_missing() {
        let dir = TempDir::new().expect("tempdir");
        let cfg = tls(&dir);
        fs::write(&cfg.cert_file, "stub").expect("stub cert");

        let err = load_or_generate_cert_key(&cfg).expect_err("partial state must error");
        let msg = format!("{err:#}");
        assert!(msg.contains("key file"), "msg={msg}");
        assert!(msg.contains("missing"), "msg={msg}");
    }

    #[test]
    fn errors_when_only_cert_missing() {
        let dir = TempDir::new().expect("tempdir");
        let cfg = tls(&dir);
        fs::write(&cfg.key_file, "stub").expect("stub key");

        let err = load_or_generate_cert_key(&cfg).expect_err("partial state must error");
        let msg = format!("{err:#}");
        assert!(msg.contains("cert file"), "msg={msg}");
        assert!(msg.contains("missing"), "msg={msg}");
    }

    #[test]
    fn loads_existing_pair_without_regenerating() {
        let dir = TempDir::new().expect("tempdir");
        let cfg = tls(&dir);

        let (_, _, first) = load_or_generate_cert_key(&cfg).expect("first call generates");
        assert!(first.was_generated);

        let cert_mtime_before = fs::metadata(&cfg.cert_file).expect("meta").mtime();
        let key_mtime_before = fs::metadata(&cfg.key_file).expect("meta").mtime();

        let (_, _, second) = load_or_generate_cert_key(&cfg).expect("second call loads");
        assert!(!second.was_generated);
        assert_eq!(
            first.cert_fingerprint_sha256,
            second.cert_fingerprint_sha256
        );

        let cert_mtime_after = fs::metadata(&cfg.cert_file).expect("meta").mtime();
        let key_mtime_after = fs::metadata(&cfg.key_file).expect("meta").mtime();
        assert_eq!(cert_mtime_before, cert_mtime_after, "cert was rewritten");
        assert_eq!(key_mtime_before, key_mtime_after, "key was rewritten");
    }

    #[test]
    fn build_sans_appends_extra_after_loopback() {
        let extra = vec!["vtl.internal".to_string(), "10.0.0.5".to_string()];
        let sans = build_sans(&extra);
        let v6_idx = sans.iter().position(|s| s == "::1").expect("::1 present");
        let extra_idx = sans
            .iter()
            .position(|s| s == "vtl.internal")
            .expect("extra present");
        assert!(
            extra_idx > v6_idx,
            "extra SANs come after the loopback trio"
        );
        assert!(sans.contains(&"10.0.0.5".to_string()));
    }

    #[test]
    fn auto_gen_writes_marker_with_fingerprint() {
        let dir = TempDir::new().expect("tempdir");
        let cfg = tls(&dir);

        let (_, _, outcome) = load_or_generate_cert_key(&cfg).expect("auto-generate");

        let marker = marker_path(&cfg.cert_file);
        let marker_fp = fs::read_to_string(&marker).expect("marker present");
        assert_eq!(marker_fp.trim(), outcome.cert_fingerprint_sha256);
        let marker_mode = fs::metadata(&marker).expect("marker meta").mode() & 0o777;
        assert_eq!(marker_mode, CERT_MODE, "marker mode");
    }

    #[test]
    fn regenerate_with_no_cert_generates_fresh() {
        let dir = TempDir::new().expect("tempdir");
        let cfg = tls(&dir);

        let outcome = regenerate_cert(&cfg).expect("fresh generate");
        assert!(outcome.prior_fingerprint.is_none());
        assert!(cfg.cert_file.exists() && cfg.key_file.exists());
        let marker_fp = fs::read_to_string(marker_path(&cfg.cert_file)).expect("marker");
        assert_eq!(marker_fp.trim(), outcome.cert_fingerprint_sha256);
    }

    #[test]
    fn regenerate_with_valid_marker_rotates() {
        let dir = TempDir::new().expect("tempdir");
        let cfg = tls(&dir);

        let (_, _, first) = load_or_generate_cert_key(&cfg).expect("first generate");
        let outcome = regenerate_cert(&cfg).expect("regenerate");

        assert_eq!(
            outcome.prior_fingerprint.as_deref(),
            Some(first.cert_fingerprint_sha256.as_str())
        );
        assert_ne!(
            outcome.cert_fingerprint_sha256,
            first.cert_fingerprint_sha256
        );
        let marker_fp = fs::read_to_string(marker_path(&cfg.cert_file)).expect("marker");
        assert_eq!(marker_fp.trim(), outcome.cert_fingerprint_sha256);
    }

    #[test]
    fn regenerate_refuses_when_marker_absent() {
        let dir = TempDir::new().expect("tempdir");
        let cfg = tls(&dir);

        load_or_generate_cert_key(&cfg).expect("generate");
        fs::remove_file(marker_path(&cfg.cert_file)).expect("drop marker");

        let err = regenerate_cert(&cfg).expect_err("must refuse without marker");
        let msg = format!("{err:#}");
        assert!(msg.contains("no"), "msg={msg}");
        assert!(msg.contains("marker"), "msg={msg}");
    }

    #[test]
    fn regenerate_refuses_on_foreign_cert() {
        let dir = TempDir::new().expect("tempdir");
        let cfg = tls(&dir);
        load_or_generate_cert_key(&cfg).expect("daemon cert");

        // A different self-signed cert generated elsewhere, dropped in
        // over our cert while the stale marker stays behind.
        let foreign_dir = TempDir::new().expect("tempdir");
        let foreign = tls(&foreign_dir);
        load_or_generate_cert_key(&foreign).expect("foreign cert");
        fs::copy(&foreign.cert_file, &cfg.cert_file).expect("swap cert");

        let err = regenerate_cert(&cfg).expect_err("must refuse foreign cert");
        let msg = format!("{err:#}");
        assert!(msg.contains("does not match"), "msg={msg}");
    }

    #[test]
    fn regenerate_bakes_in_extra_sans() {
        let dir = TempDir::new().expect("tempdir");
        let mut cfg = tls(&dir);
        cfg.extra_sans = vec!["extra.example".to_string()];

        let outcome = regenerate_cert(&cfg).expect("regenerate");
        assert!(
            outcome.sans.contains(&"extra.example".to_string()),
            "sans={:?}",
            outcome.sans
        );
    }
}
